version: '3.8'

services:
  node:
    image: node:latest
    container_name: node_ed
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

    #docker exec -it node_ed sh